#!/bin/env bash 

cd /etc/apparmor.d && doas aa-enforce \
  login \
  loginctl \
  f3brew \
  f3fix \
  f3probe \
  f3read \
  f3write \
  fail2ban-client \
  fail2ban-server \
  fatlabel \
  fatresize \
  fc-cache \
  fc-list \
  fdisk \
  ffmpeg \
  ffplay \
  ffprobe \
  file-roller \
  filecap \
  findmnt \
  firecfg \
  firefox \
  firefox-crashreporter \
  firefox-glxtest \
  firefox-kmozillahelper \
  firefox-minidump-analyzer \
  firefox-pingsender \
  firefox-plugin-container \
  firefox-vaapitest \
  firejail-default \
  firewalld \
  flatpak-portal \
  flatpak-session-helper \
  flatpak-system-helper \
  font-manager \
  fping \
  fprintd \
  freefall \
  fritzing \
  frontend \
  fsck \
  fsck-btrfs \
  fsck-ext4 \
  fsck-fat \
  fwupd \
  fwupdmgr \
  fzsftp \
  gajim \
  games-wesnoth \
  games-wesnoth-sh \
  gammastep-mine \
  ganyremote \
  gconfd \
  gdisk \
  gdk-pixbuf-query-loaders \
  geoclue \
  gio-launch-desktop \
  gio-querymodules \
  git \
  gitstatusd \
  gjs-console \
  gkbd-keyboard-display \
  glib-compile-resources \
  glib-compile-schemas \
  glib-pacrunner \
  globaltime \
  glxgears \
  glxinfo \
  gmenudbusmenuproxy \
  goa-daemon \
  goa-identity-service \
  gpa \
  gparted \
  gpartedbin \
  gpasswd \
  gpg \
  gpg-agent \
  gpg-connect-agent \
  gpgconf \
  gpgsm \
  gping \
  gpo \
  gpodder \
  gpodder-migrate2tres \
  groupadd \
  groupdel \
  groupmod \
  groups \
  grpck \
  grub-bios-setup \
  grub-check-signatures \
  grub-editenv \
  grub-file \
  grub-fstest \
  grub-glue-efi \
  grub-install \
  grub-kbdcomp \
  grub-macbless \
  grub-menulst2cfg \
  grub-mkconfig \
  grub-mkdevicemap \
  grub-mkfont \
  grub-mkimage \
  grub-mklayout \
  grub-mknetdir \
  grub-mkpasswd-pbkdf2 \
  grub-mkrelpath \
  grub-mkrescue \
  grub-mkstandalone \
  grub-mount \
  grub-multi-install \
  grub-ntldr-img \
  grub-probe \
  grub-reboot \
  grub-render-label \
  grub-script-check \
  grub-set-default \
  grub-syslinux2cfg \
  gsettings \
  gsimplecal \
  gsmartcontrol \
  gsmartcontrol-root \
  gssproxy \
  gtk-query-immodules \
  gtk-update-icon-cache \
  gzdoom \
  hardinfo \
  haveged \
  hbbr \
  hbbs \
  hciconfig \
  hddtemp \
  hdparm \
  hexchat \
  host \
  hostapd \
  hostname \
  hostnamectl \
  htop \
  hugeadm \
  hugo \
  hw-probe \
  hwinfo \
  hypnotix \
  i2cdetect \
  i3lock \
  i3lock-fancy \
  id \
  ifconfig \
  ifup \
  im-launch \
  initd-kexec \
  initd-kexec-load \
  initd-kmod \
  install-catalog \
  install-info \
  install-printerdriver \
  inxi \
  ioping \
  iotop \
  ip \
  ipcalc \
  irqbalance \
  iw \
  iwconfig \
  iwctl \
  iwd \
  iwlist \
  jdownloader \
  jgmenu \
  jmtpfs \
  k3s \
  kaccess \
  kactivitymanagerd \
  kalendarac \
  kanyremote \
  kauth-backlighthelper \
  kauth-chargethresholdhelper \
  kauth-discretegpuhelper \
  kauth-fontinst \
  kauth-kded-smart-helper \
  kauth-kinfocenter-dmidecode-helper \
  kcheckpass \
  kcminit \
  kconf_update \
  kconfig-hardened-check \
  kde-powerdevil \
  kded5 \
  keepassxc \
  keepassxc-cli \
  keepassxc-proxy \
  kernel-install \
  kerneloops \
  kerneloops-applet \
  kexec \
  kglobalaccel5 \
  kgx \
  kio_http_cache_cleaner \
  kioslave5 \
  kmod \
  kodi \
  kodi-xrandr \
  kreadconfig \
  kscreen_backend_launcher \
  kscreenlocker-greet \
  ksmserver \
  kubernetes-pause \
  kvm-ok \
  kwalletd5 \
  kwalletmanager5 \
  kwin_x11 \
  labwc \
  landscape-sysinfo \
  landscape-sysinfo.wrapper \
  language-validate \
  last \
  lastlog \
  less \
  librewolf-mine \
  libvirt-dbus \
  libvirtd \
  light \
  light-locker \
  light-locker-command \
  lightdm \
  lightdm-gtk-greeter \
  lightworks \
  lightworks-ntcardvt \
  linssid \
  linux-check-removal \
  linux-version \
  locale-gen \
  localectl \
  localepurge \
  logrotate \
  losetup \
  lsb_release \
  lsblk \
  lscpu \
  lsinitramfs \
  lspci \
  lsusb \
  lvm \
  lvmconfig \
  lvmdump \
  lvmpolld \
  lxappearance \
  lynx \
  macchanger \
  mandb \
  mbsync \
  mdevctl \
  mediainfo \
  mediainfo-gui \
  megasync \
  memtester \
  merkaartor \
  mimetype \
  minitube \
  mission-control \
  mke2fs \
  mkfs-btrfs \
  mkfs-fat \
  mkinitcpio \
  mkinitramfs \
  mkntfs \
  mkswap \
  mkvmerge \
  mkvtoolnix-gui \
  mlocate \
  modprobed-db \
  molly-guard \
  monitorix \
  mono-sgen \
  mount \
  mount-cifs \
  mount-nfs \
  mount-zfs \
  mpsyt \
  mpv \
  mtools \
  mtr \
  mtr-packet \
  mullvad-daemon \
  mullvad-gui \
  mumble \
  mumble-overlay \
  murmurd \
  mutter-x11-frames \
  nemo \
  netcap \
  nethogs \
  netstat \
  networkctl \
  networkd-dispatcher \
  newgidmap \
  newgrp \
  newuidmap \
  nfsdcld \
  nft \
  nm-daemon-helper \
  nm-dhcp-helper \
  nm-dispatcher \
  nm-iface-helper \
  nm-initrd-generator \
  nm-openvpn-auth-dialog \
  nm-openvpn-service \
  nm-openvpn-service-openvpn-helper \
  nmap \
  nmcli \
  nologin \
  nslookup \
  ntfs-3g \
  ntfs-3g-probe \
  ntfscat \
  ntfsclone \
  ntfscluster \
  ntfscmp \
  ntfscp \
  ntfsdecrypt \
  ntfsfallocate \
  ntfsfix \
  ntfsinfo \
  ntfslabel \
  ntfsls \
  ntfsmove \
  ntfsrecover \
  ntfsresize \
  ntfssecaudit \
  ntfstruncate \
  ntfsundelete \
  ntfsusermap \
  ntfswipe \
  nullmailer-send \
  numlockx \
  obamenu \
  obconf \
  obex-folder-listing \
  obexautofs \
  obexctl \
  obexd \
  obexfs \
  obexpush-atd \
  obexpushd \
  obxprop \
  on-ac-power \
  onefetch \
  openbox \
  openbox-session \
  openvpn \
  orage \
  os-prober \
  paccache \
  pacdiff \
  packagekitd \
  pacman \
  pacman-conf \
  pacman-hook-code \
  pacman-hook-dconf \
  pacman-hook-depmod \
  pacman-hook-dkms \
  pacman-hook-fontconfig \
  pacman-hook-gio \
  pacman-hook-gtk \
  pacman-hook-mkinitcpio \
  pacman-hook-mkinitcpio-remove \
  pacman-hook-perl \
  pacman-key \
  pacmd \
  pactl \
  pagesize \
  pam-auth-update \
  pam_roles \
  parted \
  partprobe \
  pass \
  pass-import \
  passwd \
  pavucontrol \
  pcb-gtk \
  pcscd \
  php-fpm \
  picom \
  pidof \
  pinentry \
  pinentry-curses \
  pinentry-gnome3 \
  pinentry-gtk-2 \
  pinentry-qt \
  pipewire \
  pipewire-pulse \
  pkcs11-register \
  pkexec \
  pkttyagent \
  plasmashell \
  plocate \
  plocate-build \
  plymouth \
  plymouth-set-default-theme \
  plymouthd \
  polipo \
  polkit-agent-helper \
  polkit-kde-authentication-agent \
  polkitd \
  popcon-largest-unused \
  popularity-contest \
  power-profiles-daemon \
  ps \
  ps-mem \
  pscap \
  psi \
  psi-plus \
  pstree \
  pulseaudio \
  pulseeffects \
  pwck \
  qbittorrent \
  qbittorrent-nox \
  qemu-ga \
  qnapi \
  qpdfview \
  qt5ct \
  qtchooser \
  qtox \
  quiterss \
  rdmsr \
  redshift \
  reflector \
  remmina \
  repo \
  reprepro \
  resize2fs \
  resolvconf \
  rfkill \
  rngd \
  rpi-imager \
  rredtool \
  rsyslogd \
  rtkit-daemon \
  rtkitctl \
  run-parts \
  runuser \
  rustdesk \
  rustdesk-utils \
  s3fs \
  samba-bgqd \
  samba-dcerpcd \
  samba-rpcd \
  samba-rpcd-classic \
  samba-rpcd-spoolss \
  sanoid \
  sbctl \
  sbin.klogd \
  sbin.syslog-ng \
  sbin.syslogd \
  scdaemon \
  scrcpy \
  scrot \
  sdcv \
  sensors \
  sensors-detect \
  setpci \
  sfdisk \
  sftp-server \
  sgdisk \
  slirp4netns \
  smartctl \
  smartd \
  smplayer \
  smtube \
  spacefm \
  spacefm-auth \
  spectre-meltdown-checker \
  speedtest \
  spflashtool \
  spice-client-glib-usb-acl-helper \
  spice-vdagent \
  spice-vdagentd \
  ss \
  ssh \
  ssh-agent \
  ssh-agent-launch \
  ssh-keygen \
  sshd \
  sshfs \
  sslocal \
  ssmanager \
  ssserver \
  ssservice \
  ssurl \
  start-pulseaudio-x11 \
  startplasma-x11 \
  startx \
  strawberry \
  strawberry-tagreader \
  su \
  sudo \
  suid3num \
  sulogin \
  swaplabel \
  swapoff \
  swapon \
  switcheroo-control \
  swtpm \
  swtpm_ioctl \
  swtpm_localca \
  swtpm_setup \
  syncoid \
  syncthing \
  system-config-printer \
  system-config-printer-applet \
  tailscale \
  tailscaled \
  tasksel \
  tftp \
  thermald \
  thinkfan \
  tint2 \
  tint2conf \
  top \
  torify \
  torsocks \
  tpacpi-bat \
  tracker-extract \
  tracker-miner \
  transmission-cli-mine \
  transmission-qt \
  tune2fs \
  ucf \
  udiskie \
  udiskie-info \
  udiskie-mount \
  udiskie-umount \
  udisksctl \
  udisksd \
  umount \
  umount.udisks2 \
  uname \
  unhide-linux \
  unhide-posix \
  unhide-rb \
  unhide-tcp \
  unix-chkpwd \
  unmkinitramfs \
  update-ca-certificates \
  update-ca-trust \
  update-command-not-found \
  update-cracklib \
  update-desktop-database \
  update-dlocatedb \
  update-grub \
  update-initramfs \
  update-mime-database \
  update-pciids \
  update-secureboot-policy \
  update-smart-drivedb \
  updatedb-mlocate \
  updatedb.plocate \
  upower \
  upowerd \
  uptime \
  uptimed \
  usb-devices \
  usbguard \
  usbguard-applet-qt \
  usbguard-daemon \
  usbguard-dbus \
  usbguard-notifier \
  uscan \
  useradd \
  userdbctl \
  userdel \
  usermod \
  users \
  utempter \
  utmpdump \
  utox \
  uupdate \
  vcsi \
  vidcutter \
  vipw-vigr \
  virt-aa-helper \
  virt-manager \
  virtinterfaced \
  virtiofsd \
  virtlockd \
  virtlogd \
  virtnetworkd \
  virtnodedevd \
  virtsecretd \
  virtstoraged \
  vnstat \
  vnstatd \
  volumeicon \
  vsftpd \
  w \
  warzone2100 \
  wavemon \
  waybar-mine \
  wg \
  wg-quick \
  wget \
  whdd \
  whereis \
  which \
  whiptail \
  who \
  whoami \
  wireplumber \
  wireshark \
  wl-copy \
  wmctrl \
  wpa-cli \
  wpa-supplicant \
  wrmsr \
  x11-xsession \
  xarchiver \
  xauth \
  xautolock \
  xbrlapi \
  xclip \
  xdg-dbus-proxy \
  xdg-desktop-icon \
  xdg-desktop-menu \
  xdg-desktop-portal \
  xdg-document-portal \
  xdg-email \
  xdg-icon-resource \
  xdg-mime \
  xdg-open \
  xdg-permission-store \
  xdg-screensaver \
  xdg-settings \
  xdg-user-dir \
  xdg-user-dirs-gtk-update \
  xdg-user-dirs-update \
  xdm-xsession \
  xdpyinfo \
  xembedsniproxy \
  xfconfd \
  xhost \
  xinit \
  xinput \
  xkbcomp \
  xorg \
  xprop \
  xrandr \
  xrdb \
  xsel \
  xset \
  xsetroot \
  xsettingsd \
  xwayland \
  yadifad \
  yt-dlp \
  zathura-mine \
  zed \
  zenmap \
  zgrep \
